### PR TITLE
chore(firestore-stripe-web-sdk): Upgrade firebase dependencies to latest

### LINKED ISSUE #453: 3 high severity vulnerabilities on installation
# Bug report

`firestore-stripe-payments`

## Describe the bug

When installing the extension with npm there is a 3 high severity vulnerabilities.

## To Reproduce

1. Open empty folder
2. Run `npm init -y`
3. Run 'npm install @stripe/firestore-stripe-payments'
4. See vulnerability
5. Run `npm audit` for more details (see below)

```
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
No fix available
node_modules/node-fetch
  @firebase/auth  <=0.0.900-exp.f919db6a9 || 0.17.0-20217250818 - 0.19.6
  Depends on vulnerable versions of node-fetch
  node_modules/@firebase/auth
    @stripe/firestore-stripe-payments  *
    Depends on vulnerable versions of @firebase/auth
    node_modules/@stripe/firestore-stripe-payments
```

## Expected behavior

There should be no vulnerabilities when installing.

## System information

- Windows

## Additional context

I think its just an issue with your dependency on `@firebase/auth`.

### PR DESCRIPTION
**Pull request by ChrisJamesC**
Fixes #453

### CODE REVIEW

**Comment by temrb** [comment]
above worked for me- not sure why it's not merged yet

**Comment by ChrisJamesC** [comment]
> above worked for me- not sure why it's not merged yet

I'm waiting for someone at stripe to enable the workflows and review the PR.

**Comment by luc122c** [comment]
Hopefully this gets merged soon. It should also fix #495?

**Comment by BenJackGill** [comment]
Any updates? Would also like to see this fixed for #453

**Comment by temrb** [comment]
> Any updates? Would also like to see this fixed for #453 

You don't need this package really. Just use main stripe package and then the firebase extension through firebase UI.

That's why I ended up doing and kind of altering some of the code here and it worked for my usecase.

Like portals etc

**Comment by vdegenne** [comment]
@ChrisJamesC Please update this pr title to `chore(firestore-stripe-web-sdk): Upgrade firebase dependencies to latest`

**Review by dackers86 — APPROVED** [review]

**Comment by dackers86** [comment]
HI @ChrisJamesC 

This looks great, could you merge with the latest `next` branch,  happy to then merge this in!

**Comment by dackers86** [comment]
@ChrisJamesC If you would still like credit for this PR, please re-open and i'll be happy to include.

Closing in the meantime.

**Comment by ChrisJamesC** [comment]
@dackers86 That's all good, thanks a lot for reviving this repo!

**Pull request closed without merging**
